# Trading Framework Configuration

# System Configuration
system:
  name: "AlgoTrading Framework"
  mode: "paper"  # Options: "backtest", "live", "paper"
  timezone: "Asia/Kolkata"
  log_level: "DEBUG"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  log_dir: "logs"
  data_dir: "data"
  output_dir: "output"
  max_threads: 20
  heartbeat_interval: 5
  max_strategy_interval: 300
  max_market_data_staleness: 60

# Logging configuration
logging:  
  log_level: "INFO"  # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL  
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"

  log_dir: "logs"
  console_output: true
  file_output: true
  json_format: false  
  capture_warnings: true  
  
  max_file_size_mb: 50
  backup_count: 5 
  
  component_levels:
    core.engine: "DEBUG"
    core.market_data: "DEBUG"
    core.order_manager: "DEBUG" 
    strategies: "DEBUG"
    brokers: "DEBUG"
    backtest: "DEBUG"
    live: "DEBUG"    
  
  error_email_config:
    enabled: false
    mailhost: "smtp.example.com"
    fromaddr: "algotrading@example.com"
    toaddrs: ["alerts@example.com"]
    subject: "AlgoTrading ERROR Alert"
    credentials:
      username: "alert_user"
      password: "alert_password"
    secure: true
  
  # Syslog configuration (optional)
  syslog_output: false
  syslog_address: "localhost:514"
  syslog_facility: 1  # LOG_USER

# --- Broker Connection Configuration --- 
broker_connections:
  # Primary connection to use for live/paper trading
  active_connection: "finvasia_live" # Name matching one of the connections below

  # Session Manager Configuration
  session_manager:
    enabled: true  # Set to false to disable shared session management
    refresh_interval_hours: 8  # How often to refresh the session token
    auto_retry_on_expiry: true  # Whether to automatically retry on session expiry
    max_retries: 3  # Maximum number of retries on session expiry

  connections:
    - connection_name: "finvasia_live"
      broker_type:    "finvasia"
      secrets:        "config/.env.finvasia"
      api:
        api_url:     "https://api.shoonya.com/NorenWClientTP/"
        timeout:     10
        max_retries: 3
        retry_delay: 1
        debug:       false

    - connection_name: "simulated_broker"
      broker_type:    "simulated"
      latency_range_ms: [20, 100]
      fill_realism:
        slippage_pct: 0.0005
      order_flow:
        # A standard place_order will become OPEN, then COMPLETE
        place_order: ["PENDING", "FILL"]

        # To test a rejection:
        # place_order: ["REJECT"] 

        # To test a partial fill then full fill:
        # place_order: ["OPEN", "PARTIAL_FILL", "COMPLETE"]

        # To test a cancellation:
        cancel_order: ["CANCELED"]

        # To test a modification that then fills:
        modify_order: ["OPEN", "COMPLETE"]
           
# --- Market Data Configuration --- 
market_data:  
  persistence:
    enabled: true
    path: "./data/processed"
    interval: 60
  
  # Performance optimizations
  use_cache: true
  cache_limit: 10000
  use_redis: false
  thread_pool_size: 4
  processing_queue_size: 10000
  batch_processing: true
  batch_size: 100
  timeframe_manager_cache_limit: 10000
  
  # Greek calculation
  calculate_greeks: true
  greeks_risk_free_rate: 0.05
  
  # Timeframe configuration
  timeframes:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "1d"
  
  live_feed_type: "finvasia" # Options: "finvasia", "simulated", "zerodha", etc.  
  feed_settings:
    finvasia:
      reconnect_interval: 5
      max_reconnect_attempts: 10
      enable_persistence: true
      persistence_path: "./data/finvasia_ticks"
      persistence_interval: 600   # 10 minutes
      max_ticks_in_memory: 20000
      cache_file: "./cache/finvasia_symbols.json"
      cache_expiry: 86400 # 24 hours

    simulated:
      indices:
        - name: "NIFTY INDEX"
          exchange: "NSE"
          spot_price: 24700
          scenario: sideways     
  
        - name: "SENSEX"
          exchange: "BSE"
          spot_price: 81100
          scenario: sideways

# Redis configuration (used if market_data.use_redis is true)
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  key_prefix: "market_data:"
  ttl: 86400

market:
  default_exchange: "NSE"
  exchanges:
    - "NSE"
    - "BSE"
    - "NFO"
    - "MCX"
  market_hours:
    start: "09:15:00"
    end: "15:30:00"
  pre_market_hours:
    start: "09:00:00"
    end: "09:15:00"
  post_market_hours:
    start: "15:30:00"
    end: "16:00:00"
  holidays: ["2025-01-26", "2025-08-15", "2025-10-02"]
  data_retention_days: 15

  # Underlying configurations (Index or Stocks)
  underlyings:
    - symbol: "NIFTY INDEX"
      exchange: "NSE"
      derivative_exchange: "NFO"
      strike_interval: 100
      expiry: "weekly"
      atm_range: 1  # Number of strikes above and below ATM
      
    - symbol: "SENSEX"
      exchange: "BSE"
      derivative_exchange: "BFO"
      strike_interval: 100
      expiry: "weekly"
      atm_range: 1

# Option manager configuration
option_manager:
  cache_size: 1000
  strike_range_count: 5
  otm_levels: 3
  update_interval: 60
  
# Event manager configuration
event_manager:
  queue_size: 5000
  process_sleep: 0.001
  enable_monitoring: true
  diagnostic_interval: 5

# Portfolio configuration
portfolio:
  initial_capital: 1000000
  base_currency: "INR"
  risk_free_rate: 0.04
  benchmark: "NIFTY"
  reporting:
    daily_email: false
    recipient: "malangshah@gmail.com"

# Risk management configuration
risk_management:
  max_drawdown: 0.05
  max_daily_loss: 0.03
  max_position_size: 0.1
  max_open_orders: 10
  max_leverage: 2.0
  position_sizing:
    default: "fixed"
    fixed_size: 1
    percent_capital: 0.02

performance:
  benchmark: "NIFTY 50"
  metrics: # Metrics to calculate and report
    - "total_return"
    - "annualized_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    # - "expectancy"
    # - "cagr"
  reporting:
    frequency: "end_of_day" # Options: "real_time", "hourly", "end_of_day"
    format: "json" # Options: "csv", "json"
    save_trades: true
    save_equity_curve: true

backtest:
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_capital: 1000000 # Use portfolio.initial_capital
  commission:
    model: "percentage"
    value: 0.0005 # 0.05%
  slippage:
    model: "percentage"
    value: 0.001 # 0.1%

# Live trading specific configuration
live:
  emergency_stop_on_broker_failure: false
  reconnect_interval: 30
  recovery_mode: "conservative"
  paper_trading_settings:
    slippage: 0.0001  # 1 basis point of slippage
    commission: 0.0005  # 5 basis points of commission

excel_monitor:
  enabled: false  # Set to true to enable the dashboard, false to disable
  path: "output/trading_dashboard.xlsx"  # Path to save the Excel dashboard
  update_interval: 2.0  # Interval in seconds for checking the update queue
  max_retries: 5  # Max retries for file operations or thread errors
  retry_delay: 3.0  # Delay in seconds between retries
  display_rows:
    orders: 10       # Max number of open orders to display
    trades: 15       # Max number of executed trades to display
    positions: 10    # Max number of positions to display
    equity_points: 20 # Max number of points for the equity curve chart

# --- Instruments --- 
# instruments:
#   - symbol: "RELIANCE-EQ"
#     id: "RELIANCE" # Unique ID if needed, otherwise symbol is used
#     instrument_type: "EQ"
#     exchange: "NSE"
#     asset_type: "equity"
#     currency: "INR"
#     tick_size: 0.05
#     lot_size: 1
#     is_tradable: true

