# Strategy configurations
strategies:  
  # atm_straddle:
  #   enabled: true
  #   type: "atm_straddle_strategy"
  #   description: "ATM Straddle strategy that buys CE and PE at ATM strike"
    
  #   # Index and symbol configurations
  #   use_options: true
  #   underlyings:
  #   - name: "NIFTY INDEX"
  #     index: true
  #     spot_exchange: NSE
  #     option_exchange: NFO
  #   - name: "SENSEX"
  #     index: true
  #     spot_exchange: BSE
  #     option_exchange: BFO
    
  #   expiry_offset: 0  # 0=current expiry, 1=next expiry
    
  #   # Timeframe configurations
  #   timeframe: "1m"
  #   additional_timeframes: ["5m"]
    
  #   # Entry and exit parameters
  #   parameters:
  #     entry_time: "09:30:00"
  #     exit_time: "15:15:00"
  #     stop_loss_percent: 30
  #     target_percent: 15
  #     trail_points: 0.25
    
  #   # Data requirements
  #   data:
  #     min_history_bars: 5
  #     warmup_bars: 2
    
  #   # Execution settings
  #   execution:
  #     order_type: "MARKET"
  #     quantity: 1
  #     slippage_percent: 0.1
    
  #   # Position management
  #   risk:
  #     max_positions: 1
  #     max_risk_per_trade: 2.0  # percentage of portfolio

  # EMA VWAP Option Strategy configuration
  ema_vwap_option:
    enabled: true
    type: "ema_vwap_option_strategy"
    description: "Option strategy based on EMA crossovers and VWAP with price retracement"
    
    # Index and symbol configurations
    use_options: true
    underlyings:
    - name: "NIFTY INDEX"
      index: true
      spot_exchange: NSE
      option_exchange: NFO
    - name: "SENSEX"
      index: true
      spot_exchange: BSE
      option_exchange: BFO
    
    expiry_offset: 0  # 0=current expiry, 1=next expiry
    
    # Timeframe configurations
    timeframe: "1m"
    additional_timeframes: ["5m"]
    
    # Entry and exit parameters
    parameters:
      entry_time: "09:30:00"
      exit_time: "15:15:00"
      fast_ema: 5
      slow_ema: 21
      retracement_percent: 70  # Percentage for retracement back to EMA21
      stop_loss_percent: 40    # 40% of capital deployed
      target_percent: 50       # 50% of capital deployed
    
    # Data requirements
    data:
      min_history_bars: 30     # Need enough bars to calculate EMAs and VWAP
      warmup_bars: 25
    
    # Execution settings
    execution:
      order_type: "MARKET"
      quantity: 1
      slippage_percent: 0.1
    
    # Position management
    risk:
      max_positions: 2        # Can have both CE and PE positions simultaneously
      max_risk_per_trade: 2.0  # percentage of portfolio

  high_frequency_momentum_option:
    enabled: true
    type: "high_frequency_momentum_option_strategy"
    description: "High-frequency momentum strategy for NIFTY and SENSEX options, aiming for >= 90% hit rate."
    
    use_options: true
    underlyings:
    - name: "NIFTY INDEX"
      index: true
      spot_exchange: NSE
      option_exchange: NFO
    - name: "SENSEX"
      index: true
      spot_exchange: BSE
      option_exchange: BFO
    
    expiry_offset: 0  # 0=current expiry, 1=next expiry
    
    timeframe: "1m" # Strategy requires 1m bars
    # additional_timeframes: [] # No other timeframes explicitly mentioned as required by the strategy code
    
    parameters:
      entry_time: "09:20:00"
      exit_time: "15:15:00"
      stop_loss_percent: 5
      target_percent: 10
      fast_ema_period: 3  # 5
      slow_ema_period: 5 # 20
      rsi_period: 5 # 14
      rsi_upper_band: 70
      rsi_lower_band: 30
      breakout_bars: 1 # 3
      cooldown_period_seconds: 300 # 5 minutes
    
    data:
      min_history_bars: 75 # Needs enough for slow_ema, rsi, breakout_bars, and some buffer (e.g., 20 + 14 + 3 + buffer)
      warmup_bars: 50 # Should be less than min_history_bars
    
    execution:
      order_type: "MARKET"
      quantity: 1 # Default quantity, can be overridden by RiskManager or specific strategy logic if needed
      slippage_percent: 0.1
    
    risk:
      max_positions: 2 # Can hold one CE and one PE, or one per underlying if configured for multiple
      max_risk_per_trade: 1.0  # percentage of portfolio, adjust as per risk appetite for high hit-rate strategy

  # trend_rider_option_buyer:
  #   enabled: true
  #   type: "trend_rider_option_buyer_strategy"
  #   description: "Option buying strategy using EMA crossover and ADX for NIFTY & SENSEX."
    
  #   # Define which underlyings this strategy instance will trade.
  #   # StrategyManager will use this to request data via DataManager for these underlyings.
  #   underlyings:
  #   - name: "NIFTY INDEX" # Must match a configured underlying in config.yaml or be discoverable
  #     index: true
  #     spot_exchange: "NSE" # Exchange of the underlying
  #     option_exchange: "NFO" # Exchange for the options
  #     # instrument_type: "INDEX" # Optional: helps DataManager/OptionManager
  #     # asset_class: "INDEX"   # Optional: helps DataManager/OptionManager
  #   - name: "SENSEX"
  #     index: true
  #     spot_exchange: "BSE"
  #     option_exchange: "BFO" # Assuming BFO for SENSEX options
  #     # instrument_type: "INDEX"
  #     # asset_class: "INDEX"
    
  #   expiry_offset: 0  # 0=current weekly expiry, 1=next weekly expiry, etc.
    
  #   # Primary timeframe for indicator calculation and signal generation on underlyings.
  #   timeframe: "5m" 
  #   # additional_timeframes: [] # No other timeframes needed by this strategy for underlyings

  #   parameters:
  #     entry_time: "09:25:00"    # Start trading after initial volatility
  #     exit_time: "15:10:00"     # Square off before market close
      
  #     fast_ema_period: 9
  #     slow_ema_period: 21
  #     adx_period: 14
  #     adx_threshold: 20         # Minimum ADX value to consider a trend strong enough
      
  #     stop_loss_percent: 25     # Stop-loss as a percentage of option entry premium
  #     target_percent: 50        # Target profit as a percentage of option entry premium
      
  #     otm_strikes_away: 0       # 0 for ATM, 1 for 1st OTM, etc.
  #     cooldown_period_seconds: 300 # 5 minutes cooldown for an underlying after an exit

  #   data:
  #     # min_history_bars: 50 # For EMA and ADX (e.g., 21 for slow_ema + 14 for ADX + buffer)
  #     # warmup_bars: 35      # Should be less than min_history_bars
  #     # These are more relevant for backtesting; for live, DataManager handles history.
  #     # BaseStrategy's max_bars_to_keep will manage DataFrame size in memory.
  #     max_bars_to_keep: 200 # Max bars to keep in memory per symbol/timeframe

  #   execution:
  #     order_type: "MARKET"    # Could be "LIMIT" with some slippage logic
  #     quantity: 1             # Base quantity in lots. Actual trade quantity from Portfolio/Risk Manager.
  #     # slippage_percent: 0.1 # For backtesting or if order execution logic uses it
    
  #   risk: # These are conceptual for the strategy; actual enforcement by RiskManager
  #     max_positions_per_underlying: 1 # Allow only one option (CE or PE) per underlying at a time
  #     # max_risk_per_trade_percent: 1.0 # e.g. 1% of capital, for RiskManager to consider

  # gamma_scalping_iv_filter:
  #   enabled: true
  #   type: "gamma_scalping_iv_filter_strategy" # Must match the name registered in StrategyRegistry
  #   description: "Gamma Scalping Straddle with IV filter for NIFTY INDEX"
    
  #   timeframe: "15m" # Primary timeframe for underlying analysis
  #   # additional_timeframes: ["1d"] # If daily data is used for IV/Consolidation and fetched this way
    
  #   underlyings: # List of underlyings this strategy instance will trade
  #     - name: "NIFTY INDEX"
  #       index: true
  #       exchange: "NSE" # Spot exchange for the underlying
  #       option_exchange: "NFO" # Options exchange

  #   parameters:
  #     iv_percentile_lookback_days: 252
  #     iv_percentile_threshold: 25.0  # Enter if IV percentile is LESS than this
  #     bb_period: 20
  #     bb_std_dev: 2.0
  #     consolidation_days: 5
  #     consolidation_max_range_percent: 1.0 # Max daily range % of current price
  #     atm_strike_proximity_percent: 0.5 # Underlying price must be within 0.5% of ATM strike

  #     profit_target_percent_on_premium: 2.0 # e.g., 2% profit on total premium paid
  #     stop_loss_percent_on_premium: 15.0  # e.g., 15% loss on total premium paid
  #     max_holding_period_hours: 24

  #     trade_entry_start_time: '09:30:00' # Start looking for entries
  #     trade_entry_end_time: '14:30:00'   # Stop looking for new entries (allows time for exit before EOD)
  #     cooldown_period_minutes: 60 # Cooldown after exiting a straddle on an underlying

  #   execution:
  #     quantity_per_leg: 1 # Number of lots for Call, and 1 for Put

  #   # Data requirements (can be used by BaseStrategy or for info)
  #   data:
  #     min_history_bars_15m: 150 # For BB (20) + Consolidation (5 days * ~26 bars/day)
  #     min_history_bars_1d: 260 # For IV percentile (252) + Consolidation (5)
  #     # warmup_bars: ...

  # iv_crush_calendar_condor:
  #   enabled: true
  #   type: "iv_crush_calendar_condor_strategy"
  #   description: "IV Crush Calendar Iron Condor for NIFTY"
  #   timeframe: "1d" # Daily check for entry logic
  #   # additional_timeframes: ["1m"] # For MTM of options if needed, handled by MarketDataEvent

  #   underlyings:
  #     - name: "NIFTY INDEX"
  #       index: true
  #       exchange: "NSE"
  #       option_exchange: "NFO"

  #   parameters:
  #     iv_skew_threshold_percent: 15.0  # Enter if 7D IV is >15% higher than 21D IV
  #     sma_period: 20
  #     sma_band_percent: 1.5 # Spot must be within SMA +/- 1.5%
      
  #     short_dte_target: 7   # Target DTE for short options
  #     long_dte_target: 21   # Target DTE for long options (calendar part)
      
  #     short_leg_delta: 16.0 # Delta for short strikes of the 7DTE condor
  #     long_wing_delta: 8.0  # Delta for long wing strikes of the 7DTE condor
  #                           # Same strikes used for 21DTE condor but opposite positions

  #     min_credit_to_cost_ratio: 1.2
  #     estimated_cost_per_leg: 30.0 # Rough estimate per leg (brokerage + slippage)

  #     profit_target_percent_of_max_profit: 60.0 # Exit if PNL reaches 60% of initial net credit
  #     stop_loss_multiplier_on_credit: 1.5     # Exit if PNL drops to -150% of initial net credit
  #     exit_before_short_expiry_days: 1        # Exit if 7DTE options have 1 or 0 DTE

  #     daily_check_time: '15:00:00' # Time to perform daily checks and potential entries

  #     vix_instrument_id: "NSE:INDIA VIX" # For VIX based position sizing (simplified)
  #     base_capital_allocation_percent: 5.0
  #     max_capital_allocation_percent_low_vix: 7.5
  #     low_vix_threshold: 15.0

  #   execution:
  #     quantity_per_spread: 1 # Number of lots for each of the 4 spreads (total 8 legs)

  # Iron Butterfly Strategy
  # iron_butterfly:
  #   enabled: true
  #   type: "iron_butterfly_strategy"
  #   description: "Iron Butterfly Options Strategy"
    
  #   # Index and symbol configurations
  #   use_options: true
  #   indices: ["BANKNIFTY"]
  #   expiry_offset: 0  # current expiry
    
  #   # Timeframe configurations
  #   timeframe: "5m"
  #   additional_timeframes: ["15m"]
    
  #   # Entry and exit parameters
  #   parameters:
  #     entry_time: "09:45:00"
  #     exit_time: "15:00:00"
  #     wings_width: 500  # points away from ATM
  #     stop_loss_percent: 40
  #     target_percent: 20
    
  #   # Data requirements
  #   data:
  #     min_history_bars: 10
  #     warmup_bars: 3
    
  #   # Execution settings
  #   execution:
  #     order_type: "LIMIT"
  #     quantity: 1
  #     slippage_percent: 0.2
    
  #   # Position management
  #   risk:
  #     max_positions: 1
  #     max_risk_per_trade: 2.5  # percentage of portfolio

  # Option EMA Crossover Strategy
  # option_ema_crossover:
  #   enabled: true
  #   type: "option_ema_crossover_strategy"
  #   description: "EMA Crossover Strategy with Option Trading"
    
  #   # Index and symbol configurations
  #   use_options: true
  #   indices: ["NIFTY", "BANKNIFTY"]
  #   expiry_offset: 0
    
  #   # Timeframe configurations
  #   timeframe: "5m"
  #   additional_timeframes: ["15m", "1h"]
    
  #   # Entry and exit parameters
  #   parameters:
  #     fast_ema: 9
  #     slow_ema: 21
  #     signal_ema: 9
  #     entry_threshold: 0.05
  #     stop_loss_percent: 25
  #     target_percent: 50
  #     use_trailing_stop: true
  #     trailing_percent: 10
    
  #   # Option selection
  #   option_selection:
  #     atm_offset: 0  # 0=ATM, 1=ITM, -1=OTM
  #     option_type: "both"  # "CE", "PE", or "both" 
  #     min_premium: 50
  #     max_premium: 500
    
  #   # Data requirements
  #   data:
  #     min_history_bars: 50
  #     warmup_bars: 25
    
  #   # Execution settings
  #   execution:
  #     order_type: "MARKET"
  #     quantity: 1
  #     slippage_percent: 0.1
    
  #   # Position management
  #   risk:
  #     max_positions: 2
  #     max_risk_per_trade: 1.5  # percentage of portfolio
      
  # # Volatility-based Strategy
  # vix_option_strategy:
  #   enabled: true
  #   type: "vix_option_strategy"
  #   description: "VIX-based option trading strategy"
    
  #   # Index and symbol configurations
  #   use_options: true
  #   indices: ["NIFTY"]
  #   additional_symbols: ["INDIA VIX"]
  #   expiry_offset: 0
    
  #   # Timeframe configurations
  #   timeframe: "5m"
  #   additional_timeframes: ["15m", "1h"]
    
  #   # Entry and exit parameters
  #   parameters:
  #     vix_threshold_high: 20
  #     vix_threshold_low: 15
  #     premium_capture_percent: 25
  #     stop_loss_percent: 50
  #     target_percent: 25
    
  #   # Option selection
  #   option_selection:
  #     high_vix_option: "PE"  # Buy PE when VIX is high
  #     low_vix_option: "CE"   # Buy CE when VIX is low
  #     atm_offset: 0          # ATM options
    
  #   # Data requirements
  #   data:
  #     min_history_bars: 30
  #     warmup_bars: 10
    
  #   # Execution settings
  #   execution:
  #     order_type: "MARKET"
  #     quantity: 1
  #     slippage_percent: 0.1
    
  #   # Position management
  #   risk:
  #     max_positions: 1
  #     max_risk_per_trade: 2.0  # percentage of portfolio

  # # Nifty ATM Straddle Strategy
  # nifty_atm_straddle:
  #   name: "NiftyATMStraddle" 
  #   type: "atm_option_strategy" 
  #   active: true
  #   universe:
  #     type: "atm_options"
  #     underlying_symbol: "NIFTY 50"
  #     underlying_exchange: "NSE"
  #     option_exchange: "NFO"
  #     expiry_offset: 0
  #     strikes_around_atm: 0
  #   parameters:
  #     strike_recheck_threshold_pct: 0.4
  #     option_strike_interval: 50.0

  # # Moving Average Crossover Strategy
  # moving_average_crossover:
  #   name: "MovingAverageCrossover"
  #   type: "moving_average_crossover"
  #   active: true
  #   universe:
  #     type: "explicit"
  #     value: ["RELIANCE-EQ", "TCS-EQ", "HDFCBANK-EQ", "INFY-EQ", "ICICIBANK-EQ", "NIFTY17APR25C22800"]
  #     min_market_cap: 10000
  #     max_stocks: 10
  #   parameters:
  #     fast_period: 9
  #     slow_period: 21
  #     signal_period: 9
  #   execution:
  #     order_type: "LIMIT"
  #     limit_price_buffer: 0.1
  #     entry_timing: "next_bar"
  #     exit_timing: "immediate"
  #     time_in_force: "DAY"
  #   risk:
  #     position_size: 5.0
  #     max_positions: 5
  #     stop_loss: 2.0
  #     trailing_stop: true
  #     trailing_stop_distance: 1.0
  #     take_profit: 5.0
  #   schedule:
  #     days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
  #     start_time: "09:20:00"
  #     end_time: "15:15:00"
  #     frequency: "1m"
  #   filters:
  #     min_volume: 100000
  #     max_spread: 0.5
  #     min_price: 100
  #     max_price: 5000
  #   fill_handling:
  #     adjust_stop_loss: true
  #     partial_fills: "accept"
  #     timeout: 60
  #   lifecycle:
  #     warmup_bars: 30
  #     cooldown_after_stop_loss: 5

  # # ATM Option EMA Crossover Strategy
  # atm_option_ema_crossover:
  #   name: "atm_option_ema_crossover"
  #   type: "atm_option_ema_crossover_strategy"
  #   active: true
  #   universe:
  #     type: "explicit"
  #     value: ["NIFTY-INDEX", "NIFTY50-INDEX", "BANKNIFTY-INDEX"]
  #   parameters:
  #     short_ema_period: 9
  #     long_ema_period: 21
  #     volume_lookback_period: 21
  #     profit_target_percent: 20.0
  #     stop_loss_percent: 20.0
  #     retracement_tolerance: 0.01
  #     timeframe: "1m"
  #     additional_timeframes: ["5m"]
  #   execution:
  #     order_type: "MARKET"
  #     entry_timing: "immediate"
  #     exit_timing: "immediate"
  #     time_in_force: "DAY"
  #   risk:
  #     position_size: 5.0
  #     max_positions: 3
  #     stop_loss: 20.0
  #     trailing_stop: false
  #     take_profit: 20.0
  #   schedule:
  #     days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
  #     start_time: "09:20:00"
  #     end_time: "15:15:00"
  #     frequency: "1m"
  #   filters:
  #     min_volume: 100
  #     max_spread: 1.0
  #   fill_handling:
  #     adjust_stop_loss: false
  #     partial_fills: "accept"
  #     timeout: 60
  #   lifecycle:
  #     warmup_bars: 30
  #     cooldown_after_stop_loss: 5


  

